AllCops:
  TargetRubyVersion: 2.1

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
